// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeviceStats device stats
//
// swagger:model DeviceStats
type DeviceStats struct {

	// connections
	Connections float64 `json:"connections,omitempty"`

	// received bytes
	ReceivedBytes float64 `json:"received_bytes,omitempty"`

	// transmitted bytes
	TransmittedBytes float64 `json:"transmitted_bytes,omitempty"`
}

// Validate validates this device stats
func (m *DeviceStats) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this device stats based on context it is used
func (m *DeviceStats) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeviceStats) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeviceStats) UnmarshalBinary(b []byte) error {
	var res DeviceStats
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
