// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IP IP
//
// swagger:model IP
type IP string

// Validate validates this IP
func (m IP) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this IP based on context it is used
func (m IP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
