// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// WireGuardKey wire guard key
//
// swagger:model WireGuardKey
type WireGuardKey string

// Validate validates this wire guard key
func (m WireGuardKey) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wire guard key based on context it is used
func (m WireGuardKey) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
