// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WireGuardPeer wire guard peer
//
// swagger:model WireGuardPeer
type WireGuardPeer struct {

	// i ps
	IPs []string `json:"ips"`

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// ps key
	PsKey string `json:"ps_key,omitempty"`

	// pub key
	PubKey string `json:"pub_key,omitempty"`
}

// Validate validates this wire guard peer
func (m *WireGuardPeer) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wire guard peer based on context it is used
func (m *WireGuardPeer) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireGuardPeer) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireGuardPeer) UnmarshalBinary(b []byte) error {
	var res WireGuardPeer
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
