// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WireguardInterfaceSpec wireguard interface spec
//
// swagger:model WireguardInterfaceSpec
type WireguardInterfaceSpec struct {

	// ports
	Ports []int64 `json:"ports"`

	// priv key
	PrivKey string `json:"priv_key,omitempty"`
}

// Validate validates this wireguard interface spec
func (m *WireguardInterfaceSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wireguard interface spec based on context it is used
func (m *WireguardInterfaceSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireguardInterfaceSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireguardInterfaceSpec) UnmarshalBinary(b []byte) error {
	var res WireguardInterfaceSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
