// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// WireguardSpec wireguard spec
//
// swagger:model WireguardSpec
type WireguardSpec struct {

	// endpoint
	Endpoint string `json:"endpoint,omitempty"`

	// ps key
	PsKey string `json:"ps_key,omitempty"`

	// pub key
	PubKey string `json:"pub_key,omitempty"`
}

// Validate validates this wireguard spec
func (m *WireguardSpec) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this wireguard spec based on context it is used
func (m *WireguardSpec) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *WireguardSpec) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WireguardSpec) UnmarshalBinary(b []byte) error {
	var res WireguardSpec
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
