// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client/public/models"
)

// BindingListReader is a Reader for the BindingList structure.
type BindingListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *BindingListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewBindingListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewBindingListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewBindingListOK creates a BindingListOK with default headers values
func NewBindingListOK() *BindingListOK {
	return &BindingListOK{}
}

/* BindingListOK describes a response with status code 200, with default header values.

ok
*/
type BindingListOK struct {
	Payload models.DeviceBindings
}

func (o *BindingListOK) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceID}/bindings/][%d] bindingListOK  %+v", 200, o.Payload)
}
func (o *BindingListOK) GetPayload() models.DeviceBindings {
	return o.Payload
}

func (o *BindingListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewBindingListDefault creates a BindingListDefault with default headers values
func NewBindingListDefault(code int) *BindingListDefault {
	return &BindingListDefault{
		_statusCode: code,
	}
}

/* BindingListDefault describes a response with status code -1, with default header values.

error
*/
type BindingListDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the binding list default response
func (o *BindingListDefault) Code() int {
	return o._statusCode
}

func (o *BindingListDefault) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceID}/bindings/][%d] BindingList default  %+v", o._statusCode, o.Payload)
}
func (o *BindingListDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *BindingListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
