// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client/public/models"
)

// GetByIDReader is a Reader for the GetByID structure.
type GetByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetByIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetByIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetByIDOK creates a GetByIDOK with default headers values
func NewGetByIDOK() *GetByIDOK {
	return &GetByIDOK{}
}

/* GetByIDOK describes a response with status code 200, with default header values.

ok
*/
type GetByIDOK struct {
	Payload *models.DeviceFullDetails
}

func (o *GetByIDOK) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceID}/][%d] getByIdOK  %+v", 200, o.Payload)
}
func (o *GetByIDOK) GetPayload() *models.DeviceFullDetails {
	return o.Payload
}

func (o *GetByIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeviceFullDetails)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetByIDDefault creates a GetByIDDefault with default headers values
func NewGetByIDDefault(code int) *GetByIDDefault {
	return &GetByIDDefault{
		_statusCode: code,
	}
}

/* GetByIDDefault describes a response with status code -1, with default header values.

error
*/
type GetByIDDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get by ID default response
func (o *GetByIDDefault) Code() int {
	return o._statusCode
}

func (o *GetByIDDefault) Error() string {
	return fmt.Sprintf("[GET /devices/{deviceID}/][%d] GetByID default  %+v", o._statusCode, o.Payload)
}
func (o *GetByIDDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetByIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
