// Code generated by go-swagger; DO NOT EDIT.

package device

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client/node/models"
)

// DevicesStatsUpdateReader is a Reader for the DevicesStatsUpdate structure.
type DevicesStatsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DevicesStatsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDevicesStatsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewDevicesStatsUpdateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDevicesStatsUpdateOK creates a DevicesStatsUpdateOK with default headers values
func NewDevicesStatsUpdateOK() *DevicesStatsUpdateOK {
	return &DevicesStatsUpdateOK{}
}

/* DevicesStatsUpdateOK describes a response with status code 200, with default header values.

ok
*/
type DevicesStatsUpdateOK struct {
}

func (o *DevicesStatsUpdateOK) Error() string {
	return fmt.Sprintf("[POST /stats/][%d] devicesStatsUpdateOK ", 200)
}

func (o *DevicesStatsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDevicesStatsUpdateDefault creates a DevicesStatsUpdateDefault with default headers values
func NewDevicesStatsUpdateDefault(code int) *DevicesStatsUpdateDefault {
	return &DevicesStatsUpdateDefault{
		_statusCode: code,
	}
}

/* DevicesStatsUpdateDefault describes a response with status code -1, with default header values.

error
*/
type DevicesStatsUpdateDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the devices stats update default response
func (o *DevicesStatsUpdateDefault) Code() int {
	return o._statusCode
}

func (o *DevicesStatsUpdateDefault) Error() string {
	return fmt.Sprintf("[POST /stats/][%d] DevicesStatsUpdate default  %+v", o._statusCode, o.Payload)
}
func (o *DevicesStatsUpdateDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *DevicesStatsUpdateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
