// Code generated by go-swagger; DO NOT EDIT.

package network

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewInterfaceListParams creates a new InterfaceListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewInterfaceListParams() *InterfaceListParams {
	return &InterfaceListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewInterfaceListParamsWithTimeout creates a new InterfaceListParams object
// with the ability to set a timeout on a request.
func NewInterfaceListParamsWithTimeout(timeout time.Duration) *InterfaceListParams {
	return &InterfaceListParams{
		timeout: timeout,
	}
}

// NewInterfaceListParamsWithContext creates a new InterfaceListParams object
// with the ability to set a context for a request.
func NewInterfaceListParamsWithContext(ctx context.Context) *InterfaceListParams {
	return &InterfaceListParams{
		Context: ctx,
	}
}

// NewInterfaceListParamsWithHTTPClient creates a new InterfaceListParams object
// with the ability to set a custom HTTPClient for a request.
func NewInterfaceListParamsWithHTTPClient(client *http.Client) *InterfaceListParams {
	return &InterfaceListParams{
		HTTPClient: client,
	}
}

/* InterfaceListParams contains all the parameters to send to the API endpoint
   for the interface list operation.

   Typically these are written to a http.Request.
*/
type InterfaceListParams struct {

	// XRelayHostname.
	XRelayHostname string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the interface list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InterfaceListParams) WithDefaults() *InterfaceListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the interface list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *InterfaceListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the interface list params
func (o *InterfaceListParams) WithTimeout(timeout time.Duration) *InterfaceListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the interface list params
func (o *InterfaceListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the interface list params
func (o *InterfaceListParams) WithContext(ctx context.Context) *InterfaceListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the interface list params
func (o *InterfaceListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the interface list params
func (o *InterfaceListParams) WithHTTPClient(client *http.Client) *InterfaceListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the interface list params
func (o *InterfaceListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithXRelayHostname adds the xRelayHostname to the interface list params
func (o *InterfaceListParams) WithXRelayHostname(xRelayHostname string) *InterfaceListParams {
	o.SetXRelayHostname(xRelayHostname)
	return o
}

// SetXRelayHostname adds the xRelayHostname to the interface list params
func (o *InterfaceListParams) SetXRelayHostname(xRelayHostname string) {
	o.XRelayHostname = xRelayHostname
}

// WriteToRequest writes these params to a swagger request
func (o *InterfaceListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param X-Relay-Hostname
	if err := r.SetHeaderParam("X-Relay-Hostname", o.XRelayHostname); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
