// Code generated by go-swagger; DO NOT EDIT.

package wireguard

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/forestvpn/go-api-client/sd/models"
)

// PeersListReader is a Reader for the PeersList structure.
type PeersListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PeersListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPeersListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPeersListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPeersListOK creates a PeersListOK with default headers values
func NewPeersListOK() *PeersListOK {
	return &PeersListOK{}
}

/* PeersListOK describes a response with status code 200, with default header values.

ok
*/
type PeersListOK struct {
	Payload models.WireGuardPeersList
}

func (o *PeersListOK) Error() string {
	return fmt.Sprintf("[GET /wg/peers/][%d] peersListOK  %+v", 200, o.Payload)
}
func (o *PeersListOK) GetPayload() models.WireGuardPeersList {
	return o.Payload
}

func (o *PeersListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPeersListDefault creates a PeersListDefault with default headers values
func NewPeersListDefault(code int) *PeersListDefault {
	return &PeersListDefault{
		_statusCode: code,
	}
}

/* PeersListDefault describes a response with status code -1, with default header values.

error
*/
type PeersListDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the peers list default response
func (o *PeersListDefault) Code() int {
	return o._statusCode
}

func (o *PeersListDefault) Error() string {
	return fmt.Sprintf("[GET /wg/peers/][%d] PeersList default  %+v", o._statusCode, o.Payload)
}
func (o *PeersListDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PeersListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
